---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/raulavila/concourse-tutorial.git

jobs:
- name: job-hello-world
  public: true
  plan:
  - get: resource-tutorial
  - task: hello-world
    config:
      platform: linux
      image: /opt/docker-images/busybox
      run:
        path: echo
        args: [{{my_argument}}]
  - task: hello-world2
    file: resource-tutorial/01_task_hello_world/task_hello_world.yml
